Repository ramiromarcosmorales/emiti-web, pull requests merged in 2025-09, with the labels that each got.

#15 doc: actualizar template pr
  .github/PULL_REQUEST_TEMPLATE/feature-template.md
Labels: documentation, devops

#17 Revert "doc: actualizar template pr"
  .github/PULL_REQUEST_TEMPLATE/feature-template.md
  changelog.md
Labels: devops

#19 docs(ia): Se modifico bloque de codigo de los prompts acorde a lo sol…
  changelog.md
  docs/02-prompts/prompts-1.md
  docs/02-prompts/prompts-2.md
  docs/02-prompts/prompts-3.md
  docs/02-prompts/prompts-4.md
  docs/02-prompts/prompts-5.md
Labels: ia

#14 Feature/doc ux readme mockup
  README.md
  changelog.md
  docs/01-mockup/mockup01-dashboard.png
  docs/01-mockup/mockup02-nueva-factura.png
  docs/01-mockup/mockup03-facturas.png
  docs/01-mockup/mockup04-configuracion.png
Labels: documentation, doc-ux

#18 Feature/coordinador setup repo and pages
  .github/ISSUE_TEMPLATE/devops.md
  .github/ISSUE_TEMPLATE/doc-ux.md
  .github/ISSUE_TEMPLATE/frontend.md
  .github/ISSUE_TEMPLATE/ia.md
  .github/PULL_REQUEST_TEMPLATE/feature-template.md
  changelog.md
Labels: enhancement, devops

#35 docs: documentar casos de prueba
  changelog.md
  docs/.DS_Store
  docs/03-testing/.gitkeep
  docs/03-testing/test-case-1.md
  docs/03-testing/test-case-2.md
  docs/03-testing/test-case-3.md
  docs/03-testing/test-case-4.md
  docs/03-testing/test-case-5.md
  docs/03-testing/testing-doc.md
  docs/screenshots/axe-dev-tools.png
  docs/screenshots/caniuse-border-radius.png
  docs/screenshots/caniuse-box-shadow.png
  docs/screenshots/caniuse-flexbox.png
  docs/screenshots/caniuse-grid.png
  docs/screenshots/chrome-desktop.jpg
  docs/screenshots/css-stats.png
  docs/screenshots/css-validation.png
  docs/screenshots/edge-desktop.jpg
  docs/screenshots/firefox-desktop.jpg
  docs/screenshots/fully-loaded-time-page-size.png
  docs/screenshots/grade.png
  docs/screenshots/html-validation.png
  docs/screenshots/ipad_air_landscape.png
  docs/screenshots/ipad_air_portrait.png
  docs/screenshots/iphone_14_pro_landscape.jpeg
  docs/screenshots/iphone_14_pro_portrait.jpeg
  docs/screenshots/lighthouse-accessibility.png
  docs/screenshots/lighthouse-report.png
  docs/screenshots/metrics.png
  docs/screenshots/performance-gtmetrix.png
  docs/screenshots/performance.png
  docs/screenshots/s23_landscape.jpg
  docs/screenshots/s23_portrait.jpg
  docs/screenshots/safari-desktop.jpg
  docs/screenshots/structure-gtmetrix.png
  docs/screenshots/wave-report.png
Labels: documentation
